name: Java CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module:
          - lanchonete-model
          - lanchonete-web

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build ${{ matrix.module }}
        working-directory: ./${{ matrix.module }}
        run: mvn -B clean verify
